# What is Tensor

In [5]:
import torch
import numpy as np

A type of order data sheet

scalar 0-D Tensor

Vector 1-D Tensor

Matrix 2-D Tensor

# How to created Tensor?

In [7]:
#1 by python list , np.array
t1 = torch.Tensor([[1,2,3],[4,5,6]])
t2 = torch.Tensor(np.arange(24).reshape(2,3,4))

In [9]:
t1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
t2

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [11]:
#2 by some function : empty ones zeros rand randint randn
torch.empty(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.zeros(1,3)

tensor([[0., 0., 0.]])

In [16]:
torch.rand(2,3,4)#[0,1)

tensor([[[0.3187, 0.5539, 0.9354, 0.4024],
         [0.5192, 0.4604, 0.4420, 0.6772],
         [0.2962, 0.1728, 0.3426, 0.3545]],

        [[0.7321, 0.5099, 0.9623, 0.7118],
         [0.9650, 0.9822, 0.6171, 0.1338],
         [0.2664, 0.3939, 0.4370, 0.5858]]])

In [17]:
torch.randint(low = 0 ,high = 10 , size = [3,4])

tensor([[7, 2, 5, 5],
        [9, 3, 4, 8],
        [6, 0, 8, 6]])

In [19]:
torch.randn([3,4])# E = 0 Var = 1

tensor([[-0.7424, -0.0775,  0.2342,  0.8501],
        [-0.0579, -0.4127,  2.0670,  0.9691],
        [-0.9250, -1.5155, -0.9247, -1.2157]])

# Some Attributes of Tensor

item() when the tensor has only a element,the tensor.item get it method 

In [21]:
t3  = torch.Tensor([[2]])

In [22]:
t3

tensor([[2.]])

In [24]:
t3.item()

2.0

numpy() make torch.tensor to numpy.ndarray

In [25]:
t2.numpy()

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32)

like numpy tensor has dim() size() and reshape()/view()

In [26]:
t2.dim()

3

In [27]:
t2.size()

torch.Size([2, 3, 4])

In [28]:
t2.view(3,2,4)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

Tensor has of course max() min() means() and so on

Futhermore transpose() t() and permute() change the view way of the 'cubic'

the dtype transform should be attention,and the default dtype is float

# Operation 

In [32]:
x = torch.ones(3,5,dtype = torch.float)

In [34]:
y = torch.rand(3,5)

In [36]:
torch.add(x,y)

tensor([[1.5670, 1.9592, 1.8663, 1.2247, 1.9387],
        [1.4041, 1.8668, 1.4370, 1.0855, 1.1656],
        [1.4847, 1.9126, 1.0244, 1.1426, 1.5524]])

In [37]:
x+y

tensor([[1.5670, 1.9592, 1.8663, 1.2247, 1.9387],
        [1.4041, 1.8668, 1.4370, 1.0855, 1.1656],
        [1.4847, 1.9126, 1.0244, 1.1426, 1.5524]])

The difference between func and func_ is that the later will change the data of the caller

In [39]:
x # x has not been modifide

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [40]:
x.add_(y)

tensor([[1.5670, 1.9592, 1.8663, 1.2247, 1.9387],
        [1.4041, 1.8668, 1.4370, 1.0855, 1.1656],
        [1.4847, 1.9126, 1.0244, 1.1426, 1.5524]])

In [41]:
x # x has been modifide

tensor([[1.5670, 1.9592, 1.8663, 1.2247, 1.9387],
        [1.4041, 1.8668, 1.4370, 1.0855, 1.1656],
        [1.4847, 1.9126, 1.0244, 1.1426, 1.5524]])

# Compute on GPU

use the method torch.cuda.is_available() , the attribute of 'device' and the .to()

In [43]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [44]:
device

device(type='cuda', index=0)

In [48]:
torch.zeros(3,4,device = device)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')

In [49]:
t2

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [50]:
t2.to(device) # change the device by .to()

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]], device='cuda:0')

# Computing the gradiant

if we want to compute gradiant of a variable,set requires_grad to True (default = False)

In [54]:
x = torch.ones(size = [2,2],requires_grad = True)

we can also change x.require_grad by:
    
    x.require_grad_(True)

In [55]:
y = x+2

In [56]:
z = 3*(y**2)

In [57]:
out = z.mean()

In [58]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [60]:
out.backward() # 反向传播

In [61]:
x.grad # 结果存在.grad 中

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

if we dont need gradient computing in some steps
just use with- method like：
with torch.no_grad():
    xxx
xxx